From 0c3f4c3eab69f10dd85af448fe4a70b26333f39a Mon Sep 17 00:00:00 2001
From: Nehal J Wani <nehaljw.kkd1@gmail.com>
Date: Sun, 24 Dec 2017 01:12:25 +0530
Subject: [PATCH 1/4] Add another fallback for test.support import

From python 2.7.14 changelog:
    - bpo-30207: To simplify backports from Python 3, the test.test_support
      module was converted into a package and renamed to test.support.  The
      test.script_helper module was moved into the test.support package.
      Names test.test_support and test.script_helper are left as aliases to
      test.support and test.support.script_helper.

So, basically, python 2.7.14 fails with:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/test/test_support.py", line 2, in <module>
    import test.support
ImportError: No module named support

This patch adds a fall back to import from backports.test.testsupport
---
 test/test_lzma.py | 8 ++++++--
 1 file changed, 6 insertions(+), 2 deletions(-)

diff --git a/test/test_lzma.py b/test/test_lzma.py
index 34264aa..173c9c1 100644
--- a/test/test_lzma.py
+++ b/test/test_lzma.py
@@ -8,8 +8,12 @@ try:
     # Try the location used on Python 3 first,
     from test.support import _4G, TESTFN, import_module, bigmemtest, run_unittest, unlink
 except ImportError:
-    # Must be under Python 2 then,
-    from test.test_support import _4G, TESTFN, import_module, bigmemtest, run_unittest, unlink
+    try:
+        # May be < Python 2.7.14
+        from test.test_support import _4G, TESTFN, import_module, bigmemtest, run_unittest, unlink
+    except ImportError:
+        # May be >=Python 2.7.14, <3
+        from future.backports.test.support import _4G, TESTFN, import_module, bigmemtest, run_unittest, unlink
 
 import inspect
 if "size" not in inspect.getargspec(bigmemtest).args:
-- 
2.14.3

